a = input('digite algo: ')
print('o tipo primitivo desse valor e', type(a))
print('so tem espacos?',a.isspace())
print('e um numero?',a.isnumeric())
print('e alfabetico?',a.isalpha())
print('e alfanumerico?',a.isalnum())
print('e maiusculo?',a.isupper())
print('e minusculo?',a.islower())
print('esta capitalizda',a.istitle())